[project]
name = "robot-api-automation"
version = "0.2.0"
description = "Robot Framework API automation project organized by tests and reusable resources."
readme = "README.md"
requires-python = ">=3.10,<3.14"
authors = [
    { name = "Ney Backes" }
]
dependencies = [
    "robotframework>=7.0,<8.0",
    "robotframework-requests>=0.9.7,<0.10.0",
    "requests>=2.32.0,<3.0.0",
    "faker>=37.0.0,<38.0.0",
]

[dependency-groups]
dev = [
    "taskipy (>=1.14.1,<2.0.0)"
]

[tool.taskipy.tasks]
test = "robot -d reports tests/"
test_login = "robot -d reports tests/login/"
test_users = "robot -d reports tests/users/"

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
